import { chromium, devices } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ ...devices["iPhone 13"] });
const p = await ctx.newPage();
const errs=[]; p.on("pageerror",e=>errs.push(String(e)));
await p.goto("http://localhost:3114/suivi/box",{waitUntil:"networkidle"});
console.log("bandeau :", await p.locator("text=/locataires? sans box/").innerText().catch(()=>"ABSENT"));
await p.locator("li button").first().click();
await p.waitForTimeout(400);
const d = p.getByRole("dialog");
console.log("bloc Locataire :", await d.locator("text=Locataire").isVisible());
const btn = d.getByRole("button", { name: /Affecter un locataire/ });
console.log("bouton :", await btn.innerText().catch(()=>"ABSENT"));
await btn.click(); await p.waitForTimeout(300);
console.log("candidats proposés :", await d.locator("div.max-h-64 button").count());
await p.screenshot({ path: process.argv[2]+"/shot-affect.png" });
console.log("erreurs :", errs.length ? errs.slice(0,3) : "aucune");
await b.close();
